### ISSUE TITLE
总是需要重新登录

### ISSUE THREAD

**Issue by zouyangpengfei** [LstHeart/vscode-wxread#10]
能不能当选项卡关闭时也保持登录状态 感觉一会就掉线了

**Comment by LstHeart** [comment]
> 能不能当选项卡关闭时也保持登录状态 感觉一会就掉线了

@zouyangpengfei 选项卡关闭后是会保持登陆状态的(未清空cookie)，目前我这边没出现过这种情况，你可以尝试重新安装插件再试试看

**Comment by zouyangpengfei** [comment]
嗯好的谢谢

**Comment by LstHeart** [comment]
@zouyangpengfei  确实存在90分钟后需要重新登录的情况，建议更新插件版本到`0.0.14`，针对此问题作了修复；

后续若还有问题，可以到这个 #12 里面讨论，这个 Issue 就先关掉了
