### ISSUE TITLE
如何解决远程无法使用的问题？（问题标题已修改）

### ISSUE THREAD

**Issue by Malibu351** [LstHeart/vscode-wxread#11]
请问一下有平替方法吗，或者有没有好的解决思路

**Comment by LstHeart** [comment]
> 请问一下有平替方法吗，或者有没有好的解决思路

@Malibu351 目前这个插件还是可以正常使用的啊，你那边用的什么版本的VSCODE? 能否提供更详细的信息看看。

我这边是正常的

![image](https://github.com/LstHeart/vscode-wxread/assets/18585439/260ba261-fedc-44f3-be6a-5deddd2299f2)

**Comment by Malibu351** [comment]
感谢回复
这个是我vscode的版本信息：

> 版本: 1.80.1 (user setup)
> 提交: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
> 日期: 2023-07-12T17:22:07.651Z
> 电子: 22.3.14
> ElectronBuildId: 21893604
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.22000

以及我确认一下，是这个插件嘛
![image](https://github.com/LstHeart/vscode-wxread/assets/57163565/7a6c073d-a6fd-4171-94a5-aea5e74a4800)

**Comment by Malibu351** [comment]
> > 请问一下有平替方法吗，或者有没有好的解决思路
> 
> @Malibu351 目前这个插件还是可以正常使用的啊，你那边用的什么版本的VSCODE? 能否提供更详细的信息看看。
> 
> 我这边是正常的
> 
> ![image](https://user-images.githubusercontent.com/18585439/256193558-260ba261-fedc-44f3-be6a-5deddd2299f2.png)

感谢回复，这个是我的vscode版本信息：
版本: 1.80.1 (user setup)
提交: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
日期: 2023-07-12T17:22:07.651Z
电子: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22000

以及这个是插件的版本
![image](https://github.com/LstHeart/vscode-wxread/assets/57163565/f51259c2-a13d-401b-9689-f54db095d82d)

**Comment by LstHeart** [comment]
@Malibu351 我刚刚把版本也升级到1.80.1了，这个插件也还是可以用的，你要不卸载之后，再重装试试？另外你是无法登录还是其他什么问题？

![image](https://github.com/LstHeart/vscode-wxread/assets/18585439/ea0bba23-6a49-4923-8224-881e19b6dff6)
![image](https://github.com/LstHeart/vscode-wxread/assets/18585439/d070f84c-bc6c-41ac-91ef-084a40d56321)

**Comment by Malibu351** [comment]
> @Malibu351 我刚刚把版本也升级到1.80.1了，这个插件也还是可以用的，你要不卸载之后，再重装试试？另外你是无法登录还是其他什么问题？
> 
> ![image](https://user-images.githubusercontent.com/18585439/256201131-ea0bba23-6a49-4923-8224-881e19b6dff6.png) ![image](https://user-images.githubusercontent.com/18585439/256201254-d070f84c-bc6c-41ac-91ef-084a40d56321.png)

昨天下班后忘记回复了不好意思，我安装并且打开之后并无内容加载
![image](https://github.com/LstHeart/vscode-wxread/assets/57163565/4be5e706-24d4-44b7-bb07-0f2973f0c5e0)

一直是这样子的，没任何反应不知道是什么情况

**Comment by Malibu351** [comment]
@LstHeart 您好，我解决我的问题了，首先是远程remote-ssh链接服务器的话，就算在服务器上装了插件也无法正常使用，一直是白屏（可能是无法加载内容），得先开启一个本地的vscode窗口，在其中登录打开小说之后，不关闭窗口，在远程vscode窗口重新加载就就可以使用了，然后就可以关闭本地的窗口。我也不知道是为什么，但我试了一下解决了我的问题，如果您有什么好的方案能让这个过程简单一些就更好了

**Comment by Malibu351** [comment]
@LstHeart 将extention.js的文件中关于loaclhost的部分替换为远程服务器的ip之后，在remote-ssh的情况下也能够微信阅读不再是白屏了，但是每次点击登录显示的内容都是“二维码无效”，不断刷新也没有什么办法，请问这个该怎么解决呢

**Comment by LstHeart** [comment]
@Malibu351 我当初并没有考虑远程开发环境用这个插件的场景😂
不过我尝试了一下，貌似不用设定远程服务器，直接转发端口就可以和本地一样了，你可以看看下面的截图试试

![image](https://github.com/LstHeart/vscode-wxread/assets/18585439/fbeda18f-a3b0-44a0-862c-acaca2103112)

**Comment by Malibu351** [comment]
@LstHeart 嗯嗯，完美解决问题了hhh太感谢您啦！

**Comment by LstHeart** [comment]
@Malibu351 我有更新一版插件`0.0.14`，远程环境现在可以自动转发端口了

**Comment by Malibu351** [comment]
@LstHeart 感谢作者！已经更新并且使用了！
