### ISSUE TITLE
插件扫码登录微信读书两个小时左右, 就会登录失效

### ISSUE THREAD

**Issue by Y-JiaCheng** [LstHeart/vscode-wxread#12]
具体什么时候开始已经忘记了, 目前是这样
具体出现的问题:
1、无法长期保存登录信息了, 我记得之前用的时候, 我哪怕好几天没开, 他也能正常保持登录状态
2、扫码登录之后, 大约两小时就会登录失效的问题, 我测试了一下谷歌浏览器不会有这个问题, 且可以长期保持登录状态

大佬可以帮忙看看吗

**Comment by Malibu351** [comment]
我这边打开微信读书后是白屏无法加载内容，有时候加载出来也只能点击书本查看信息，无法登录无法阅读，vscode版本是1.8，请问一下你这边有遇到这个问题吗，怎么解决的呢

**Comment by Y-JiaCheng** [comment]
> 

我没有这种情况, 我 vscode 是 1.80.1, 可以正常打开和阅读, 你会不会有可能是宽度太小了, 微信阅读的页面就是宽度太小会隐藏顶部的登录按钮, 你拉长宽度就会出现顶部的登录按钮

**Comment by Malibu351** [comment]
@Y-JiaCheng 我解决了我的问题，本地是没问题的，但是远程remote有问题，得先在本地开启并且正常使用之后，远程才可以正常使用，这时候关闭本地也没问题了

**Comment by Y-JiaCheng** [comment]
@Malibu351 解决了就好, 虽然没懂远程和本地的区别哈哈哈哈哈, 可惜我的问题还没得到解决,

主要还是要研究下微信读书是针对什么进行判断登录失效的, 估计要加上这个东西

大佬不知道啥时候有空理我

**Comment by LstHeart** [comment]
@Y-JiaCheng 好像确实有这个情况，我记得以前版本的VSCODE，微信登录的cookie是能保留很久的，不确定和版本有没有关系；
另外chrome网页版本正常，就vscode有问题，很奇怪，得研究一下

**Comment by Y-JiaCheng** [comment]
@LstHeart 我估计是因为微信阅读更新了, 现在扫码有一个 24 小时自动退出的功能, 可能是这个问题, 估计又新加了什么请求头估计; 
另外就是我发现如果缩小宽度到手机屏幕的宽度,页面的文字会全屏, 右侧会被吃掉一点点, 那一列字会被吃掉一半左右, 看了下宽度被设置为 101.5% 这是有什么说法吗

**Comment by LstHeart** [comment]
> @LstHeart 我估计是因为微信阅读更新了, 现在扫码有一个 24 小时自动退出的功能, 可能是这个问题, 估计又新加了什么请求头估计; 另外就是我发现如果缩小宽度到手机屏幕的宽度,页面的文字会全屏, 右侧会被吃掉一点点, 那一列字会被吃掉一半左右, 看了下宽度被设置为 101.5% 这是有什么说法吗

@Y-JiaCheng 
- 宽度设为101.5%的原因是为了隐藏微信阅读右侧的滚动条; 
不过我这边好像没碰到页面文字全屏的时候，右侧的字会被吃掉的情况。我更新了一版，新增了配置项`Hide Scrollbar`用来控制页面宽度（默认隐藏滚动条）

- 扫码登录两小时后失效的问题，也有调整一下，更新插件到最新即可; 
官方设定的cookie时效是90分钟。在浏览器上，阅读时会如果`wr_skey`失效，则会自动调用`/web/login/renewal`接口，携带包含`wr_fp`的cookie发送续订请求，延长`wr_skey`的时效；
但在VSCode端转发的请求并没有包含`wr_fp`这个cookie，因此扫码登录90分钟后必须要重新扫码才行。

综上，建议更新插件版本到`0.0.14`，后续有问题可以继续讨论~😁

**Comment by Y-JiaCheng** [comment]
@LstHeart 感谢! 已经更新好了, 目前功能都正常使用
