### ISSUE TITLE
微信读书直接封号了

### ISSUE THREAD

**Issue by dahangda** [LstHeart/vscode-wxread#14]
版本: 1.83.1
提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc
日期: 2023-10-10T23:46:55.789Z (2 个月前)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.4.0

**Comment by LstHeart** [comment]
@dahangda 我这边目前还没出现这种情况，可能与用户使用方式有关系（如果总是关闭退出可能会不断的刷cookie），不过目前微信读书已经不允许第三方插件用了，凉凉，还是老老实实用官方的吧
