### ISSUE TITLE
希望可以将标签上的 "微信读书" 设置为可以自定义编辑

### ISSUE THREAD

**Issue by lurched** [LstHeart/vscode-wxread#3]
还有标签页上的微信读书logo也是能否设置为不显示

**Comment by LstHeart** [comment]
> 还有标签页上的微信读书logo也是能否设置为不显示

变成这样？
![299563cee7abd3ceadfe9f626489e7a](https://user-images.githubusercontent.com/18585439/169737519-1cb9d924-77b7-4d12-9bb5-e14472253ff0.png)
![image](https://user-images.githubusercontent.com/18585439/169737502-dccab578-92cd-406d-8b67-bf8d07481c96.png)

**Comment by LstHeart** [comment]
@lurched 感谢建议，我这边已经改了一版了，通过配置项去控制显示logo和自定义标题，你可以更新看看

**Comment by lurched** [comment]
@LstHeart 完美符合预期👍
