### ISSUE TITLE
扫码登录没反应是为啥😂

### ISSUE THREAD

**Issue by eefeng** [LstHeart/vscode-wxread#6]

**Comment by LstHeart** [comment]
@eefeng 是最新版本，扫码登录没跳转吗？

**Comment by cn-qlg** [comment]
https://github.com/JackieZheng/WeReadForVSCode/issues/1#issuecomment-1097461416
大佬这是发现原来的没人维护，自己又重新开发了一个吗

**Comment by LstHeart** [comment]
> [JackieZheng/WeReadForVSCode#1 (comment)](https://github.com/JackieZheng/WeReadForVSCode/issues/1#issuecomment-1097461416) 大佬这是发现原来的没人维护，自己又重新开发了一个吗

算是吧，用了之前提到的反向代理；
不过其实他原来的这个，在低版本的vscode里面是可以用的；

**Comment by LstHeart** [comment]
@eefeng 不知道你那边还存不存在问题，目前我这边是不存在无法扫码登录的；如果还存在我们再进一步沟通，这个issue我就先关了
