### ISSUE TITLE
[希望]大哥能添加一个控制页面opacity的配置项吗？

### ISSUE THREAD

**Issue by SimoralX** [LstHeart/vscode-wxread#7]
如题，请问大哥是否有时间开发一个控制页面 **opacity** 的配置项？

**Comment by LstHeart** [comment]
> 如题，请问大哥是否有时间开发一个控制页面 **opacity** 的配置项？

@SimoralX 你指的是微信读书页面的 opacity 吗？

**Comment by SimoralX** [comment]
> > 如题，请问大哥是否有时间开发一个控制页面 **opacity** 的配置项？
> 
> @SimoralX 你指的是微信读书页面的 opacity 吗？目前有办法通过配置项，实现调整 panel 的 opacity,但微信读书内部的opacity 无法调整，可以看看panel opacity的效果：
> 
> ![image](https://user-images.githubusercontent.com/18585439/179254750-e1ac6168-0129-4c83-b4b4-ae52a8742a83.png)

对，就调整页面样式的 opacity 就行。就是如图的效果就行。

**Comment by LstHeart** [comment]
@SimoralX opacity的功能已更新，默认配置是1，可自行修改，谢谢反馈！😁

**Comment by SimoralX** [comment]
> @SimoralX opacity的功能已更新，默认配置是1，可自行修改，谢谢反馈！😁

大哥牛啊👍👍👍
